### ISSUE TITLE
Reorganise schema files

### ISSUE THREAD

**Issue by afrittoli** [cdevents/sdk-go#23]
In the current generated schema, `type` is at the bottom of each schema, and we would like instead to move it to the top for readability. 

Schemas are currently generated from the go structs. 
Check if it's possible to change this in the code that generates the json schemas.

For instance: 

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cdevents.dev/draft/schema/artifact-packaged-event",
  "properties": {
    "context": { (...)
    },
    "subject": { (...)
    },
    "customData": { (...)
    },
  },
  "additionalProperties": false,
  "type": "object",
  "required": [
    "context",
    "subject"
  ]
}
```

should be:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://cdevents.dev/draft/schema/artifact-packaged-event",
  "type": "object",
  "properties": {
    "context": { (...)
    },
    "subject": { (...)
    },
    "customData": { (...)
    },
  },
  "additionalProperties": false,
  "required": [
    "context",
    "subject"
  ]
}
```

**Comment by randomnoise** [comment]
I took a look at this @afrittoli, the ordering is managed by [invopop/jsonschema](https://github.com/invopop/jsonschema) package.

In order to change this, `Type` must come before `Properties` in `Schema` struct in [the reflection code](https://github.com/invopop/jsonschema/blob/679d2ebe09b8f687b85ae6a662370edc22196c09/reflect.go#L50-L56).

I gave it a shot; made a fork, changed the ordering. It works but I think it is out of scope of the cdevents repo.

**Comment by afrittoli** [comment]
Schema files are now taken via git submodule from the spec repo - at least for testing.
For validation, they are generated on the fly, and only kept in memory, so the order of keys does not matter there.

It is a bit confusing the way it is now, because we use one jsonschema library to generate the schemas from the struct, a different one to validate against schemas loaded from file, and a different library for extra validation, so there is space for improvement, but I think we could close this specific issue now.

Thank you for your work on this @randomnoise !
